# Generated by Django 4.1.6 on 2023-03-10 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='regalo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(default=0)),
                ('clientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secundario.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrada', models.DateTimeField(auto_now_add=True)),
                ('hora_salida', models.DateTimeField()),
                ('consola', models.IntegerField(choices=[('1', 'Primero'), ('1', 'Segundo'), ('1', 'Tercero'), ('1', 'Cuarto'), ('1', 'Quinto')])),
                ('mando', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=1)),
                ('clientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secundario.cliente')),
                ('juegos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secundario.juego')),
            ],
        ),
    ]
