# Generated by Django 4.1.6 on 2023-03-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='consola',
            field=models.CharField(choices=[('1', 'Primero'), ('1', 'Segundo'), ('1', 'Tercero'), ('1', 'Cuarto'), ('1', 'Quinto')], max_length=50),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='hora_entrada',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='mando',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=50),
        ),
    ]
