# Generated by Django 4.1.6 on 2023-03-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secundario', '0002_alter_alquiler_consola_alter_alquiler_hora_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='consola',
            field=models.CharField(choices=[('Primero', 'Primero'), ('Segundo', 'Segundo'), ('Tercero', 'Tercero'), ('Cuarto', 'Cuarto'), ('Quinto', 'Quinto')], max_length=10),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='mando',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1),
        ),
        migrations.DeleteModel(
            name='regalo',
        ),
    ]
